### ISSUE TITLE
Ability to override SceneName

### ISSUE THREAD

**Issue by IvanMurzak** [Lazy-Solutions/AdvancedSceneManager#1]
Would be awesome to have ability to override scene name in any entity. Maybe would be better to call it “Scene Variants” (related to prefab variants).

I work on a project where need to load different scenes collections in case if the device is iPad. 
That is an example how I had implemented it on my own without the plugin.

![C98562BE-FEB2-4E94-8934-E7978180A0C2](https://user-images.githubusercontent.com/9135028/175756193-d7af6e77-7c25-4b2d-90ca-4efc60d887bc.jpeg)

**Comment by Zumwani** [comment]
Hi, thanks for the suggestion, we are always looking to improve ASM.

My co-worker and I have been talking and we both agree that taking a string based approach is not something we want to pursue due to one of the core pillars of ASM being to get rid of magical strings everywhere, since they can very easily break due to forgetfulness, lack of communication, or just misspelling.

We did discuss some other ideas though, such as being able to override scenes in collections depending on platform, or more generic solutions such as checking overridden platforms list in scene operation / build settings and just replacing reference. 

The thing is though, profiles already kind-of solve this use case, and yes, it might be a bit of a hassle to keep settings synced, but this would ensure that each platform would have its own scenes and settings, if any different settings are needed.

The thing we are worried about, is just the fact that once we do add overrides like this, we'll probably receive even more requests to allow even more things to be overridden, and at some point we'd be essentially at profile switching anyways.

Sorry if this is not the answer you wanted, but we'll keep thinking about it, and hopefully we might come up with a better solution in the future.

**Comment by IvanMurzak** [comment]
Thanks for reply. I agree with you about scene names as strings. That is bad idea to use in project strings like that.

Anyway, I talked about ability to swap(override) scenes to load by custom rules. In my current project the rules sounds like: need to load scenes A B C for phones (iOS + Android) and load scenes A E F for tablets (iOS + Android).

**Comment by Zumwani** [comment]
Hi, my co-worker and I have discussed this a bit more. We have a prototype, which still relies on profiles though, that hopefully helps with this scenario.

ProfileDependentScene, it is a separate scriptable object which can be created like a normal scriptable object through: Project window > right click > Advanced Scene Manager > Profile dependent scene. It takes a dictionary of Profile and Scene, and when its Open() method is called, it'll select the correct scene and open it, like a normal scene.

This means you'll have to create a Phone profile and a Tablet profile, and assign them to a profile in a ProfileDependentScene. You'll be able to use the scriptable object similar to Scene scriptable object, with the caveat that it cannot be assigned to a collection, but it can still be used like a scene in UnityEvent and from code.

UnityPackage has been uploaded to patches:
https://github.com/Lazy-Solutions/AdvancedSceneManager/tree/main/patches
(profile-dependent-scene-and-collections.unitypackage)

**Comment by IvanMurzak** [comment]
@Zumwani thank you! It should work
