### ISSUE TITLE
Many interactions want to rename the profile asset

### ISSUE THREAD

**Issue by punkkills** [Lazy-Solutions/AdvancedSceneManager#2]
Repro: 

1. I have one profile, which is active named "dev"..
![image](https://github.com/Lazy-Solutions/AdvancedSceneManager/assets/10160691/2001d327-698f-45b1-bb4b-9dadfb902207)
2.  I create a new collection with the new collection button, I get a new collection with the name "New Collection"
3. I click the vertical ... to rename the new collection.
4. I change the Title to my desired name say "Level Explore"
![image](https://github.com/Lazy-Solutions/AdvancedSceneManager/assets/10160691/eaf8588a-03d4-412c-826e-f81efaef316f)
5. I get a "Confirm Move" prompt in unity
6. Click ok to confirm the move, observe the dev profile asset has been renamed to LevelExplore
![image](https://github.com/Lazy-Solutions/AdvancedSceneManager/assets/10160691/5ed4a0dd-c231-46d5-a37a-ede8e4316119)
Clicking the active profile name also reveals the altered profile name.
![image](https://github.com/Lazy-Solutions/AdvancedSceneManager/assets/10160691/13459c90-050c-405f-a62a-cdadd3f66583)

I feel like have seen other cases where changing the name of a thing wants to rename the profile, but I don't have specific repro steps.

**Comment by punkkills** [comment]
For a bit of context, I am on Unity 2022.3.18
Asset store ASM 2.0.0
With latest overlay 2.0.29

**Comment by Zumwani** [comment]
Hi, thank you for the bug report.

I've taken a look, and yeah, it seems like when a collection has been created, an AssetDatabase.IsSubAsset(this) returns false, which lead to profile being renamed instead, since collections are saved as sub assets under profile. This code should have been removed after we had decided what how we wanted collections to be stored, but never was, somehow this slipped under the radar when testing, sorry about that.

It has been fixed in the latest patch.

I had a quick look around to see any other instances of parent asset rename, but couldn't find anything of note for any similar issues, but if any more cases appears, don't hesitate to make another bug report ☺️
